//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapeMoraleModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class morale_stats
    {
        public string MORALE { get; set; }
        public long COUNT { get; set; }
    }
}
